// Config plugin: compile the `fmt` pod as C++17.
//
// fmt 11.0.x (bundled with React Native 0.79/0.80) fails to compile with the
// Xcode 26 clang because its `consteval` format-string checks are rejected.
// Building that one pod as C++17 disables the consteval path. This lives in a
// config plugin because ios/ is generated by `expo prebuild` (CNG).
const { withPodfile } = require('expo/config-plugins');

const MARKER = '# [withFmtCxx17]';
const SNIPPET = `
    ${MARKER} fmt 11.0.x + Xcode 26 clang: build fmt as C++17 (no consteval)
    installer.pods_project.targets.each do |t|
      next unless t.name == 'fmt'
      t.build_configurations.each do |bc|
        bc.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
      end
    end
`;

module.exports = function withFmtCxx17(config) {
  return withPodfile(config, (cfg) => {
    const { contents } = cfg.modResults;
    if (!contents.includes(MARKER)) {
      cfg.modResults.contents = contents.replace(
        // Must run after react_native_post_install, which sets the C++ standard.
        /react_native_post_install\([\s\S]*?\n\s*\)\n/,
        (m) => `${m}${SNIPPET}`,
      );
    }
    return cfg;
  });
};
