// Config plugin: per-pod build-setting fixes for the generated Podfile.
//
// ios/ is generated by `expo prebuild` (CNG), so Podfile tweaks live here.
//
// 1. fmt 11.0.x (bundled with React Native 0.79/0.80) fails to compile with the
//    Xcode 26 clang because its `consteval` format-string checks are rejected.
//    Building that one pod as C++17 disables the consteval path.
// 2. react-native-maps' Objective-C headers import React headers that are not
//    modular. With `useFrameworks: 'static'` (required by react-native-firebase)
//    clang turns that into -Werror on RN 0.81+, so allow non-modular includes
//    for the maps pods only.
const { withPodfile } = require('expo/config-plugins');

const MARKER = '# [withPodBuildFixes]';
const SNIPPET = `
    ${MARKER} per-pod build settings (see app/plugins/withPodBuildFixes.js)
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |bc|
        if t.name == 'fmt'
          bc.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end
        if ['react-native-maps', 'react-native-google-maps'].include?(t.name)
          bc.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        end
      end
    end
`;

module.exports = function withPodBuildFixes(config) {
  return withPodfile(config, (cfg) => {
    const { contents } = cfg.modResults;
    if (!contents.includes(MARKER)) {
      cfg.modResults.contents = contents.replace(
        // Must run after react_native_post_install, which sets the C++ standard.
        /react_native_post_install\([\s\S]*?\n\s*\)\n/,
        (m) => `${m}${SNIPPET}`,
      );
    }
    return cfg;
  });
};
