import { StatusBar } from 'expo-status-bar';
import { useEffect, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';

interface GasPrice {
  name: string,
  currency: string,
  gasoline: number
}

interface KeyValue {
  text: string,
  value: number,
}

interface TripDistance {
  distance: KeyValue,
  duration: KeyValue,
  status: string
}

export default function App() {

  const [data, setData] = useState<Array<GasPrice>>();
  const [distance, setDistance] = useState<TripDistance>();
  const [tripCost, setCost] = useState<number>();


  // Fetch data from the Node server
  useEffect(() => {
    // This is the URL that should be generated by localtunnel
    fetch('http://carpoolcalc.loca.lt/gas-prices')
      .then((res) => res.json())
      .then((json) => {
        console.log(json);
        setData(json);
      })
      .catch((error) => console.log(error))
  }, []);

  useEffect(() => {
    fetch('http://carpoolcalc.loca.lt/distances/?start=Waterloo Ontario&end=Calgary Alberta')
      .then((res) => res.json())
      .then((json) => {
        console.log(json);
        setDistance(json);
      })
      .catch((error) => console.log(error))
  }, []);

  useEffect(() => {
    fetch('http://carpoolcalc.loca.lt/trip-cost/?start=Waterloo Ontario&end=Calgary Alberta')
      .then((res) => res.json())
      .then((json) => {
        console.log(json);
        setCost(json.cost);
      })
      .catch((error) => console.log(error))
  }, []);


  return (
    <View style={styles.container}>
      <Text style={{fontWeight: 'bold'}}>Open up App.tsx to start working on your app!</Text>
      {data?.map(el => <Text key={el.name}>{`${el.name} price = $${el.gasoline}`}</Text>)}
      {distance ? <Text>Trip will be {distance.distance.text} and will take {distance.duration.text}</Text> : <></>}
      {tripCost ? <Text>Trip will cost: ${tripCost}</Text> : <></>}
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
