require('dotenv').config();

// This project uses Continuous Native Generation (CNG): `ios/` and `android/` are
// generated by `npx expo prebuild` from this file and are not checked in.
// Put native customizations here (or in a config plugin), never in the generated dirs.

// Which Firebase project the native Firebase config files (used by
// @react-native-firebase) point at: 'dev' (northern-bot-301518) or 'prod' (gasmeup-7ce5f).
// Set per EAS build profile in eas.json and by the local `ios`/`android` npm scripts.
// Defaults to 'prod' so an unconfigured release build never talks to the dev project.
const FIREBASE_ENV = process.env.FIREBASE_ENV === 'dev' ? 'dev' : 'prod';
const firebaseFileSuffix = FIREBASE_ENV === 'dev' ? 'Dev' : 'Prod';

// Google Maps SDK for iOS key (react-native-maps uses PROVIDER_GOOGLE). Set
// GOOGLE_IOS_SDK_KEY in the local .env and in the EAS environment. It is compiled
// into the iOS binary (unavoidable for the Maps SDK), so restrict it in GCP to the
// iOS bundle id com.Virintus.GasMeUp and the Maps SDK for iOS.
// Missing key: warn for local work; fail every EAS build, which would
// otherwise ship with blank Google maps.
const GOOGLE_IOS_SDK_KEY = process.env.GOOGLE_IOS_SDK_KEY;
if (!GOOGLE_IOS_SDK_KEY) {
  const message = 'GOOGLE_IOS_SDK_KEY is not set: Google Maps will not render on iOS. Add it to app/.env (local) or the EAS environment.';
  if (process.env.EAS_BUILD === 'true') {
    throw new Error(message);
  }
  // eslint-disable-next-line no-console
  console.warn(`\u26a0\ufe0f  ${message}`);
}

// Splitwise dev client id: DEV_SPLITWISE_CLIENT_ID (documented name) or
// SPLITWISE_DEV_CLIENT_ID (the name used in existing .env files).
const DEV_SPLITWISE_CLIENT_ID = process.env.DEV_SPLITWISE_CLIENT_ID || process.env.SPLITWISE_DEV_CLIENT_ID;

module.exports = {
  name: 'GasMeUp',
  slug: 'gas-me-up',
  owner: 'mmcardle',
  originalFullName: '@mmcardle/GasMeUp',
  version: '1.2.0',
  orientation: 'portrait',
  icon: './assets/car.png',
  updates: {
    fallbackToCacheTimeout: 0,
    url: 'https://u.expo.dev/ca421c93-c21f-4e6b-a62c-52b626a5bbac',
  },
  assetBundlePatterns: [
    '**/*',
  ],
  ios: {
    supportsTablet: false,
    bundleIdentifier: 'com.Virintus.GasMeUp',
    buildNumber: '1.2.1',
    appleTeamId: '2Q4CXG64VY',
    config: {
      usesNonExemptEncryption: false,
    },
    googleServicesFile: `./GoogleService-Info-${firebaseFileSuffix}.plist`,
    infoPlist: {
      UIBackgroundModes: ['location'],
      NSLocationAlwaysUsageDescription: 'GasMeUp will access your location for functionality purposes only. One example of this would be to allow you to start tracking your location to record your trip manually in the background while driving.',
      NSLocationWhenInUseUsageDescription: "GasMeUp will access your location for functionality purposes only. Some examples of this would be to allow you to use your 'Current Location' as a start or end point or to determine which region's gas price to default to.",
      NSLocationAlwaysAndWhenInUseUsageDescription: 'GasMeUp will access your location for functionality purposes only. One example of this would be to allow you to start tracking your location to record your trip manually in the background while driving.',
    },
    // Ported from the previously checked-in ios/GasMeUp/PrivacyInfo.xcprivacy
    privacyManifests: {
      NSPrivacyAccessedAPITypes: [
        {
          NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategoryFileTimestamp',
          NSPrivacyAccessedAPITypeReasons: ['C617.1', '0A2A.1', '3B52.1'],
        },
        {
          NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategoryUserDefaults',
          NSPrivacyAccessedAPITypeReasons: ['CA92.1', '1C8F.1', 'C56D.1'],
        },
        {
          NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategorySystemBootTime',
          NSPrivacyAccessedAPITypeReasons: ['35F9.1'],
        },
        {
          NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategoryDiskSpace',
          NSPrivacyAccessedAPITypeReasons: ['E174.1', '85F4.1'],
        },
      ],
      NSPrivacyCollectedDataTypes: [],
      NSPrivacyTracking: false,
    },
  },
  android: {
    adaptiveIcon: {
      foregroundImage: './assets/adaptive-icon.png',
      backgroundColor: '#FFFFFF',
    },
    package: 'com.Virintus.GasMeUp',
    googleServicesFile: `./google-services-${firebaseFileSuffix}.json`,
    versionCode: 470010200,
  },
  extra: {
    eas: {
      projectId: 'ca421c93-c21f-4e6b-a62c-52b626a5bbac',
    },
    // Firebase
    firebaseAPIKey: process.env.FIREBASE_API_KEY,
    prodFirebaseAPIKey: process.env.PROD_FIREBASE_API_KEY,

    // `/server` API
    apiKey: process.env.API_KEY,
    useDevAPI: process.env.USE_DEV_API,
    devAPIURL: process.env.DEV_API_URL,

    // Splitwise (public OAuth client ids only; the consumer secret lives on the
    // server, which performs the code -> token exchange at POST /splitwise/token)
    splitwiseClientID: process.env.SPLITWISE_CLIENT_ID,
    splitwiseDevClientID: DEV_SPLITWISE_CLIENT_ID,

    // Nothing secret may go in `extra`: it is readable from the app bundle.
  },
  // Runtime (EAS Update compatibility). The `fingerprint` policy hashes the native
  // project (SDK, native deps, config plugins, native config), so the runtime changes
  // automatically whenever native code changes and OTA updates can never reach an
  // incompatible binary, without relying on a manual `version` bump.
  // (Previously a fixed '1.69.0'; SDK 57 binaries must not receive updates built for it.)
  runtimeVersion: { policy: 'fingerprint' },
  plugins: [
    'expo-apple-authentication',
    'expo-asset',
    'expo-web-browser',
    // Replaces the legacy top-level `splash` field (same image/colour; the full-screen
    // image mode keeps the previous iOS storyboard layout).
    [
      'expo-splash-screen',
      {
        image: './assets/splash-screen.png',
        resizeMode: 'contain',
        backgroundColor: '#6F61FE',
        enableFullScreenImage_legacy: true,
      },
    ],
    'expo-font',
    'expo-notifications',
    // Firebase via CocoaPods: RNFB's default SPM resolution is incompatible with the
    // static frameworks (`useFrameworks: 'static'`) that react-native-firebase requires.
    ['@react-native-firebase/app', { ios: { disableSPM: true } }],
    '@react-native-firebase/auth',
    // Google Maps provider on iOS (react-native-maps >= 1.22 ships its own plugin;
    // it replaces the legacy `ios.config.googleMapsApiKey` field).
    ['react-native-maps', GOOGLE_IOS_SDK_KEY ? { iosGoogleMapsApiKey: GOOGLE_IOS_SDK_KEY } : {}],
    [
      'expo-build-properties',
      {
        ios: {
          useFrameworks: 'static',
        },
      },
    ],
  ],
  scheme: 'gas-me-up',
  privacy: 'public',
  jsEngine: 'hermes',
};
